### ISSUE TITLE
Extension does not include the application Id and scope for the token request.

### ISSUE THREAD

**Issue by 3goats** [gdbarron/MachineIdentityExtension#2]
Is it possible to provide the application Id and scope for the token request when using the `getToken` action ?

![image](https://user-images.githubusercontent.com/555399/132008922-41a7a50c-a87c-4ab5-bdb6-c38c8a643f15.png)

**Comment by gdbarron** [comment]
Added to version 1.0 of the extension.  If already using the task, be sure to change the task version from 0.* to 1.*.
