### ISSUE TITLE
Extension would not verify after installing in AzureDevOpsServer2019-onprem

### ISSUE THREAD

**Issue by asifibrahim** [gdbarron/MachineIdentityExtension#8]
# Environment

```
Operating System:
Extension version: 1.2.0
```
# Actual behavior
i have uploaded screenshot.  I was able to install extension in my on-prem Azure DevOps Server 2019 but it fails verification with error in screenshot.

in case screenshot doesn't upload:

Error in screenshot is:
Task definition input action and Task definition input serverType must belong to same group as they are dependent inputs for Task with ID fe725709.......

# Screenshots
![image](https://user-images.githubusercontent.com/29954280/227269112-d4fd9410-47c0-463b-8bef-a66cd93cff8b.png)

**Comment by gdbarron** [comment]
Hi @asifibrahim, thanks for reporting this.  I think I know what the issue is...looking at it...

**Comment by gdbarron** [comment]
I don't have an on Premise server to test with, but I believe the change I made will fix the issue. Can you please test and let me know?
